### ISSUE TITLE
100 Year Domain Term in checkout

### ISSUE THREAD

**Issue by zander13auto** [Automattic/Centurions#2]
- [x] [Feedback Doc](https://docs.google.com/document/d/1EtkgsgvNovgFPGZwQewL_UqHfOdiiW4W0FAnFuTQvB8/edit?usp=sharing)
- [ ] P2 post
- [ ] [ Create billing plan for 100-year domain #1069 ](https://github.com/Automattic/nomado-issues/issues/1069)
- [ ] [ Checkout page: Show the 100-year term below the 10 years term #1072 ](https://github.com/Automattic/nomado-issues/issues/1072)
- [ ] [ Checkout page: When user selects 100-year term, show specific benefits of 100-year domains in the sidebar #1073 ](https://github.com/Automattic/nomado-issues/issues/1073)
- [ ] [ Backend: Mark domains bought with 100-year domain term with the 100-year flag and register them for 10 years #1075 ](https://github.com/Automattic/nomado-issues/issues/1075)
- [ ] [Email: Create a branded 100-year receipt #1076 ](https://github.com/Automattic/nomado-issues/issues/1076)
- [ ] [ Email: Send the branded receipt instead of the regular one if the purchase only includes #1077 ](https://github.com/Automattic/nomado-issues/issues/1077)
- [ ] [ Email: Create 100-year welcome email #1078 ](https://github.com/Automattic/nomado-issues/issues/1078)
- [ ] [ Domain management page: hide renew option and toggling auto-renew on or off for 100 year domains #1080 ](https://github.com/Automattic/nomado-issues/issues/1080)
- [ ] [ Create new vendor string for the 100 year domain search page #1083 ](https://github.com/Automattic/nomado-issues/issues/1083)
- [ ] [Email: Update ICANN required emails to mention particularities of the 100-year domain for all customers #1084 ](https://github.com/Automattic/nomado-issues/issues/1084)
- [ ] [ Add 100 Year Domains customizations to the domain transfer flow #1085 ](https://github.com/Automattic/nomado-issues/issues/1085)
- [ ] [ Emails: Prevent "new domain" email from being sent to 100-year domains #1093 ](https://github.com/Automattic/nomado-issues/issues/1093)
- [ ] [ Backend: Exclude 100-year domains from Domain Medic checks #1094 ](https://github.com/Automattic/nomado-issues/issues/1094)
```[tasklist]
### Tasks
```
